language: bash
dist: xenial
if: tag IS blank
before_install:
    - sudo apt-get update  
    - sudo apt-get install -y latexmk texlive-* wget
addons:
    apt:
        update: true
script:
    - sudo ./scripts/prepare_trusty.sh
    - echo '$latex = '\''echo X | latex -interaction=errorstopmode %O %S'\' > ~/.latexmkrc
    - ./scripts/build_all.sh
before_deploy:
    - git config --local user.name "SPbSU-CV-Lab CI"
    - git config --local user.email "dmitriy.korchemkin+spbsu-cv@gmail.com"
    - git tag "CI-$(date +%Y-%m-%d_%H-%M-%S)-$(git describe --always)"
deploy:
    provider: releases
    api_key:
        secure: jmADpRBaZG4WbknLGVF7xGNt0u/pFLbt3jGAJq5HMZ2rPcF3+8npno5uPmvgLOl47CxXOYw7qUHe0gp4jUjjI4xmI27gVvjQ640hEfHoXT+jS/i57DbiHmNTeF+Ubm0pN4lJ+yk6yXA0GQPqK9q+DL6bRd+JbK1dC3kgJmvQDB7fioXiuoq/yZF0veYxiaOSTpiKd1eS1OJEXsBjm04Pjn25Yz1i38W+uNfBmnCK7/94mIvfKGekwEi/N+o8EoNV7lG5u44xn8j+zDUTet/7A66RVrLScL/iCoSoefByvPYfdFsuoIVJqPAGOqsQEa7lQAZkRvl5CMYsHDUGOK2yY/iS5w6sACzGeE0lUBs85CX6sSLX6XLaGfdfUWu3Zf0xO+L4gs9soAVzVZtqFGRMqLKLzikoYFRt2Vdjtoeb/vP3in0ZAJ9EVp/yyvbL9eWzAp1nqbs95Tz6Vlc/JOxVuEOWUJF05OnkynLXIKZEC+M3+ilCZgv3mw9HVzsq9pFVTCRZkI3FErXyYRkF0hMzfsH5sD2jb71iiwbWatObc6P7qLQIi+Qn4OLNWmENqvA/wSLrLiOhwUoYhn1OFBoxOzsIhf/RcQTAq1jsSMkmuFHUivojk9p04ccg1flTN18s9/i12s7SUrrFfCKavBvCMB7RK22IEFV2sI+wukdA9As=
    file_glob: true
    skip_cleanup: true
    file: ./build_artifacts/*tar.gz
    on:
        repo: CV-Lab-SPbSU/seminar
